// table data for all the options
const ComponentData = [
  {
    id: 0,
    _read: false,
    researcher_id: "10001",
    direct_to: "10001",
    type: 1,
    icon: "",
    image: "",
    link: "",
    title: "New Message",
    description: "You have new message from THIS project chat!",
  },
  {
    id: 0,
    _read: false,
    researcher_id: "10001",
    direct_to: "10001",
    type: 1,
    icon: "",
    image: "",
    link: "",
    title: "New Message",
    description: "You have new message from THIS project chat!",
  },
  {
    id: 0,
    _read: false,
    researcher_id: "10001",
    direct_to: "10001",
    type: 1,
    icon: "",
    image: "",
    link: "",
    title: "New Message",
    description: "You have new message from THIS project chat!",
  },
  {
    id: 0,
    _read: false,
    researcher_id: "10001",
    direct_to: "10001",
    type: 1,
    icon: "",
    image: "",
    link: "",
    title: "New Message",
    description: "You have new message from THIS project chat!",
  },
];

export { ComponentData, NotificationData };
